INFO 2024-04-07 20:28:05,850 views 10344 4732 Посещение страницы "о себе"
INFO 2024-04-07 20:28:05,852 basehttp 10344 4732 "GET /about/ HTTP/1.1" 200 408
WARNING 2024-04-07 20:28:07,844 log 10344 4732 Not Found: /фищге
WARNING 2024-04-07 20:28:07,845 basehttp 10344 4732 "GET /%D1%84%D0%B8%D1%89%D0%B3%D0%B5 HTTP/1.1" 404 2459
INFO 2024-04-07 20:28:12,435 views 10344 4732 Посещение страницы "о себе"
INFO 2024-04-07 20:28:12,436 basehttp 10344 4732 "GET /about/ HTTP/1.1" 200 408
INFO 2024-04-08 18:10:58,123 autoreload 8264 14864 Watching for file changes with StatReloader
INFO 2024-04-08 18:11:04,796 views 8264 11336 Посещение страницы "главная"
INFO 2024-04-08 18:11:04,805 basehttp 8264 11336 "GET / HTTP/1.1" 200 240
INFO 2024-04-08 18:11:10,081 views 8264 11336 Посещение страницы "о себе"
INFO 2024-04-08 18:11:10,085 basehttp 8264 11336 "GET /about/ HTTP/1.1" 200 408
INFO 2024-04-09 18:39:43,939 autoreload 4428 10084 Watching for file changes with StatReloader
INFO 2024-04-11 12:52:32,764 autoreload 384 12664 Watching for file changes with StatReloader
WARNING 2024-04-11 12:52:35,925 log 384 604 Not Found: /
WARNING 2024-04-11 12:52:35,929 basehttp 384 604 "GET / HTTP/1.1" 404 2283
WARNING 2024-04-11 12:52:36,024 log 384 604 Not Found: /favicon.ico
WARNING 2024-04-11 12:52:36,024 basehttp 384 604 "GET /favicon.ico HTTP/1.1" 404 2334
INFO 2024-04-12 14:19:39,914 autoreload 14656 11172 Watching for file changes with StatReloader
WARNING 2024-04-12 14:19:43,085 log 14656 9460 Not Found: /
WARNING 2024-04-12 14:19:43,085 basehttp 14656 9460 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 14:19:55,637 views 14656 9460 Посещение страницы hw_app3.views: index
ERROR 2024-04-12 14:19:55,701 log 14656 9460 Internal Server Error: /homework3/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 13, in index
    return render(request, 'hw3_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3_app/index.html
ERROR 2024-04-12 14:19:55,701 basehttp 14656 9460 "GET /homework3/ HTTP/1.1" 500 80691
INFO 2024-04-12 14:21:10,008 autoreload 14656 11172 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\urls.py changed, reloading.
INFO 2024-04-12 14:21:10,850 autoreload 14776 12948 Watching for file changes with StatReloader
WARNING 2024-04-12 14:21:12,402 log 14776 3328 Not Found: /
WARNING 2024-04-12 14:21:12,403 basehttp 14776 3328 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 14:21:20,740 views 14776 3328 Посещение страницы hw_app3.views: index
ERROR 2024-04-12 14:21:20,815 log 14776 3328 Internal Server Error: /homework3/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 13, in index
    return render(request, 'hw_app3/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-12 14:21:20,822 basehttp 14776 3328 "GET /homework3/ HTTP/1.1" 500 125463
INFO 2024-04-12 14:24:16,110 views 14776 3328 Посещение страницы hw_app3.views: index
INFO 2024-04-12 14:24:16,116 basehttp 14776 3328 "GET /homework3/ HTTP/1.1" 200 433
WARNING 2024-04-12 14:24:44,795 log 14776 3328 Not Found: /homework3/client_orders_view/
WARNING 2024-04-12 14:24:44,796 basehttp 14776 3328 "GET /homework3/client_orders_view/ HTTP/1.1" 404 2956
WARNING 2024-04-12 14:25:24,724 log 14776 3328 Not Found: /homework3/ client/1/orders/
WARNING 2024-04-12 14:25:24,724 basehttp 14776 3328 "GET /homework3/%20client/1/orders/ HTTP/1.1" 404 2952
ERROR 2024-04-12 14:25:40,902 log 14776 3328 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:25:40,917 basehttp 14776 3328 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75006
ERROR 2024-04-12 14:26:58,996 log 14776 3328 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:26:58,996 basehttp 14776 3328 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75143
ERROR 2024-04-12 14:27:01,595 log 14776 3328 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:27:01,595 basehttp 14776 3328 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75143
WARNING 2024-04-12 14:27:49,060 log 14776 3328 Not Found: /homework3/client
WARNING 2024-04-12 14:27:49,061 basehttp 14776 3328 "GET /homework3/client HTTP/1.1" 404 2917
ERROR 2024-04-12 14:28:12,775 log 14776 3328 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:28:12,775 basehttp 14776 3328 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75006
INFO 2024-04-12 14:37:49,881 autoreload 7344 13644 Watching for file changes with StatReloader
WARNING 2024-04-12 14:37:57,934 log 7344 12584 Not Found: /
WARNING 2024-04-12 14:37:57,937 basehttp 7344 12584 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 14:38:06,725 views 7344 12584 Посещение страницы hw_app3.views: index
INFO 2024-04-12 14:38:06,732 basehttp 7344 12584 "GET /homework3/ HTTP/1.1" 200 433
INFO 2024-04-12 14:38:17,809 basehttp 7344 12584 "GET /homework3 HTTP/1.1" 301 0
INFO 2024-04-12 14:38:17,813 views 7344 8556 Посещение страницы hw_app3.views: index
INFO 2024-04-12 14:38:17,814 basehttp 7344 8556 "GET /homework3/ HTTP/1.1" 200 433
ERROR 2024-04-12 14:38:43,359 log 7344 8556 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:38:43,361 basehttp 7344 8556 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75006
INFO 2024-04-12 15:09:26,515 autoreload 11664 2892 Watching for file changes with StatReloader
WARNING 2024-04-12 15:09:28,819 log 11664 12532 Not Found: /
WARNING 2024-04-12 15:09:28,821 basehttp 11664 12532 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 15:09:37,605 views 11664 12532 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:09:37,625 basehttp 11664 12532 "GET /homework3/ HTTP/1.1" 200 433
ERROR 2024-04-12 15:10:13,563 log 11664 12532 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders.html
ERROR 2024-04-12 15:10:13,572 basehttp 11664 12532 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85314
ERROR 2024-04-12 15:10:15,557 log 11664 12532 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders.html
ERROR 2024-04-12 15:10:15,564 basehttp 11664 12532 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85040
INFO 2024-04-12 15:12:03,819 autoreload 11664 2892 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py changed, reloading.
INFO 2024-04-12 15:12:05,572 autoreload 14344 7176 Watching for file changes with StatReloader
ERROR 2024-04-12 15:12:06,503 log 14344 14316 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders_view.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders_view.html
ERROR 2024-04-12 15:12:06,509 basehttp 14344 14316 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85257
ERROR 2024-04-12 15:12:09,490 log 14344 14316 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders_view.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders_view.html
ERROR 2024-04-12 15:12:09,505 basehttp 14344 14316 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85257
ERROR 2024-04-12 15:15:33,935 log 14344 14316 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders_view.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders_view.html
ERROR 2024-04-12 15:15:33,944 basehttp 14344 14316 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85257
INFO 2024-04-12 15:16:52,201 autoreload 14344 7176 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\urls.py changed, reloading.
INFO 2024-04-12 15:16:53,854 autoreload 15196 13944 Watching for file changes with StatReloader
ERROR 2024-04-12 15:16:56,857 log 15196 14016 Internal Server Error: /homework3/client/1/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders_view.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders_view.html
ERROR 2024-04-12 15:16:56,868 basehttp 15196 14016 "GET /homework3/client/1/ HTTP/1.1" 500 85036
INFO 2024-04-12 15:18:41,572 autoreload 15196 13944 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\urls.py changed, reloading.
INFO 2024-04-12 15:18:43,536 autoreload 7528 9616 Watching for file changes with StatReloader
WARNING 2024-04-12 15:18:43,976 log 7528 9384 Not Found: /homework3/client/1/
WARNING 2024-04-12 15:18:43,978 basehttp 7528 9384 "GET /homework3/client/1/ HTTP/1.1" 404 2926
WARNING 2024-04-12 15:18:56,773 log 7528 9384 Not Found: /homework3/client/1//orders/
WARNING 2024-04-12 15:18:56,775 basehttp 7528 9384 "GET /homework3/client/1//orders/ HTTP/1.1" 404 2950
INFO 2024-04-12 15:19:00,690 basehttp 7528 9384 "GET /homework3/client/1/orders/ HTTP/1.1" 200 319
ERROR 2024-04-12 15:19:25,477 log 7528 9384 Internal Server Error: /homework3/client/0/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 15:19:25,483 basehttp 7528 9384 "GET /homework3/client/0/orders/ HTTP/1.1" 500 75759
INFO 2024-04-12 15:19:33,017 basehttp 7528 9384 "GET /homework3/client/2/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:21:23,334 autoreload 7528 9616 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py changed, reloading.
INFO 2024-04-12 15:21:25,694 autoreload 10920 7176 Watching for file changes with StatReloader
INFO 2024-04-12 15:21:26,074 basehttp 10920 580 "GET /homework3/client/2/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:21:34,918 basehttp 10920 580 "GET /homework3/client/1/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:21:37,871 basehttp 10920 580 "GET /homework3/client/1/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:21:58,349 basehttp 10920 580 "GET /homework3/client/4/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:27:52,049 views 10920 11152 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:27:52,052 basehttp 10920 11152 "GET /homework3/ HTTP/1.1" 200 433
INFO 2024-04-12 15:33:11,603 autoreload 10920 7176 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\models.py changed, reloading.
INFO 2024-04-12 15:33:13,045 autoreload 14828 5692 Watching for file changes with StatReloader
INFO 2024-04-12 15:34:26,273 autoreload 14476 14556 Watching for file changes with StatReloader
WARNING 2024-04-12 15:34:28,276 log 14476 12424 Not Found: /
WARNING 2024-04-12 15:34:28,279 basehttp 14476 12424 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 15:34:44,601 views 14476 12424 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:34:44,617 basehttp 14476 12424 "GET /homework3/ HTTP/1.1" 200 433
INFO 2024-04-12 15:35:08,618 basehttp 14476 12424 "GET /homework3/client/1/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:35:14,906 basehttp 14476 12424 "GET /homework3/client/2/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:35:20,030 basehttp 14476 12424 "GET /homework3/client/5/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:35:41,745 basehttp 14476 12424 "GET /homework3/client/4/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:39:15,649 basehttp 14476 12424 "GET /homework3/client/4/orders/ HTTP/1.1" 200 1034
INFO 2024-04-12 15:39:22,838 views 14476 12424 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:39:22,842 basehttp 14476 12424 "GET /homework3/ HTTP/1.1" 200 433
INFO 2024-04-12 15:41:18,711 views 14476 12424 Посещение страницы hw_app3.views: index
ERROR 2024-04-12 15:41:18,797 log 14476 12424 Internal Server Error: /homework3/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: hw_app3.base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 13, in index
    return render(request, 'hw_app3/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: hw_app3.base.html
ERROR 2024-04-12 15:41:18,808 basehttp 14476 12424 "GET /homework3/ HTTP/1.1" 500 125824
INFO 2024-04-12 15:41:47,759 views 14476 12424 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:41:47,766 basehttp 14476 12424 "GET /homework3/ HTTP/1.1" 200 326
INFO 2024-04-12 15:41:55,437 basehttp 14476 12424 "GET /homework3/client/4/orders/ HTTP/1.1" 200 1034
INFO 2024-04-12 15:42:26,236 basehttp 14476 12424 "GET /homework3/client/1/orders/ HTTP/1.1" 200 674
INFO 2024-04-13 22:10:01,657 autoreload 8820 11164 Watching for file changes with StatReloader
INFO 2024-04-13 22:17:20,518 autoreload 5544 3560 Watching for file changes with StatReloader
WARNING 2024-04-13 22:17:24,031 log 5544 12120 Not Found: /
WARNING 2024-04-13 22:17:24,031 basehttp 5544 12120 "GET / HTTP/1.1" 404 2503
WARNING 2024-04-13 22:17:24,206 log 5544 12120 Not Found: /favicon.ico
WARNING 2024-04-13 22:17:24,218 basehttp 5544 12120 "GET /favicon.ico HTTP/1.1" 404 2554
INFO 2024-04-13 22:17:41,782 views 5544 12120 Посещение страницы hw_app4.views: index
INFO 2024-04-13 22:17:41,794 basehttp 5544 12120 "GET /homework4/ HTTP/1.1" 200 326
INFO 2024-04-13 22:18:05,622 views 5544 12120 Посещение страницы hw_app4.views: about
INFO 2024-04-13 22:18:05,625 basehttp 5544 12120 "GET /homework4/about/ HTTP/1.1" 200 279
WARNING 2024-04-13 22:18:22,496 log 5544 12120 Not Found: /homework4/about/upload/
WARNING 2024-04-13 22:18:22,498 basehttp 5544 12120 "GET /homework4/about/upload/ HTTP/1.1" 404 3233
ERROR 2024-04-13 22:18:50,139 log 5544 12120 Internal Server Error: /homework4/upload/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\views.py", line 60, in upload_image
    return render(request, 'hw_app4/upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-13 22:18:50,153 basehttp 5544 12120 "GET /homework4/upload/ HTTP/1.1" 500 127614
INFO 2024-04-13 22:20:42,860 basehttp 5544 12120 "GET /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-13 22:22:54,650 basehttp 5544 12120 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 11:48:00,366 autoreload 11064 12072 Watching for file changes with StatReloader
WARNING 2024-04-14 11:48:04,158 log 11064 11848 Not Found: /
WARNING 2024-04-14 11:48:04,161 basehttp 11064 11848 "GET / HTTP/1.1" 404 2503
WARNING 2024-04-14 11:48:04,545 log 11064 11848 Not Found: /favicon.ico
WARNING 2024-04-14 11:48:04,561 basehttp 11064 11848 "GET /favicon.ico HTTP/1.1" 404 2554
INFO 2024-04-14 11:48:18,860 views 11064 11848 Посещение страницы hw_app4.views: index
INFO 2024-04-14 11:48:18,917 basehttp 11064 11848 "GET /homework4/ HTTP/1.1" 200 326
INFO 2024-04-14 11:48:38,897 basehttp 11064 11848 "GET /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 11:48:50,021 basehttp 11064 11848 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 11:53:33,694 autoreload 3868 228 Watching for file changes with StatReloader
INFO 2024-04-14 11:54:26,233 autoreload 2636 7208 Watching for file changes with StatReloader
WARNING 2024-04-14 11:54:28,202 log 2636 11728 Not Found: /
WARNING 2024-04-14 11:54:28,216 basehttp 2636 11728 "GET / HTTP/1.1" 404 2503
INFO 2024-04-14 11:54:39,873 basehttp 2636 11728 "GET /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 11:54:45,096 basehttp 2636 11728 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 12:07:47,868 autoreload 6364 380 Watching for file changes with StatReloader
INFO 2024-04-14 12:07:57,814 basehttp 6364 11800 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 12:08:02,714 basehttp 6364 11800 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 17:08:07,811 autoreload 13272 11296 Watching for file changes with StatReloader
WARNING 2024-04-14 17:08:09,871 log 13272 2612 Not Found: /
WARNING 2024-04-14 17:08:09,896 basehttp 13272 2612 "GET / HTTP/1.1" 404 2503
INFO 2024-04-14 17:08:18,684 basehttp 13272 2612 "GET /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 17:08:41,568 basehttp 13272 2612 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 17:17:03,737 autoreload 13272 11296 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\views.py changed, reloading.
INFO 2024-04-14 17:17:07,170 autoreload 7624 12392 Watching for file changes with StatReloader
INFO 2024-04-14 22:04:24,208 autoreload 11008 12992 Watching for file changes with StatReloader
WARNING 2024-04-14 22:04:26,336 log 11008 15284 Not Found: /
WARNING 2024-04-14 22:04:26,338 basehttp 11008 15284 "GET / HTTP/1.1" 404 2503
INFO 2024-04-14 22:04:35,801 basehttp 11008 15284 "GET /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 22:04:41,750 basehttp 11008 15284 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 22:30:16,325 autoreload 11544 5220 Watching for file changes with StatReloader
ERROR 2024-04-14 22:30:22,591 log 11544 13132 Internal Server Error: /homework4/upload/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\views.py", line 55, in upload_image
    image = form.cleaned_data['image']
            ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'image'
ERROR 2024-04-14 22:30:22,593 basehttp 11544 13132 "POST /homework4/upload/ HTTP/1.1" 500 68093
INFO 2024-04-14 22:31:16,266 basehttp 11544 13132 "GET /homework4/upload HTTP/1.1" 301 0
INFO 2024-04-14 22:31:16,279 basehttp 11544 6536 "GET /homework4/upload/ HTTP/1.1" 200 514
ERROR 2024-04-14 22:32:06,356 log 11544 6536 Internal Server Error: /homework4/upload/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\views.py", line 55, in upload_image
    image = form.cleaned_data['image']
            ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'image'
ERROR 2024-04-14 22:32:06,359 basehttp 11544 6536 "POST /homework4/upload/ HTTP/1.1" 500 67582
INFO 2024-04-14 22:33:43,242 autoreload 11544 5220 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\forms.py changed, reloading.
INFO 2024-04-14 22:33:44,199 autoreload 7640 3296 Watching for file changes with StatReloader
INFO 2024-04-14 22:34:10,267 autoreload 7640 3296 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\models.py changed, reloading.
INFO 2024-04-14 22:34:11,260 autoreload 4640 14644 Watching for file changes with StatReloader
INFO 2024-04-14 23:02:20,899 autoreload 8084 9792 Watching for file changes with StatReloader
WARNING 2024-04-14 23:02:22,760 log 8084 12084 Not Found: /
WARNING 2024-04-14 23:02:22,764 basehttp 8084 12084 "GET / HTTP/1.1" 404 2503
INFO 2024-04-14 23:02:32,702 basehttp 8084 12084 "GET /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 23:02:39,058 basehttp 8084 12084 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 23:06:18,533 autoreload 13264 11736 Watching for file changes with StatReloader
INFO 2024-04-14 23:07:05,827 autoreload 13264 11736 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\forms.py changed, reloading.
INFO 2024-04-14 23:07:06,602 autoreload 6912 14216 Watching for file changes with StatReloader
WARNING 2024-04-14 23:07:08,333 log 6912 13340 Not Found: /
WARNING 2024-04-14 23:07:08,335 basehttp 6912 13340 "GET / HTTP/1.1" 404 2503
INFO 2024-04-14 23:07:19,284 basehttp 6912 13340 "GET /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-14 23:07:24,496 basehttp 6912 13340 "POST /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-15 18:59:45,264 autoreload 12136 13868 Watching for file changes with StatReloader
WARNING 2024-04-15 18:59:47,859 log 12136 5992 Not Found: /
WARNING 2024-04-15 18:59:47,865 basehttp 12136 5992 "GET / HTTP/1.1" 404 2503
WARNING 2024-04-15 18:59:48,042 log 12136 5992 Not Found: /favicon.ico
WARNING 2024-04-15 18:59:48,050 basehttp 12136 5992 "GET /favicon.ico HTTP/1.1" 404 2554
INFO 2024-04-15 19:02:03,493 autoreload 12136 13868 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\migrations\0001_initial.py changed, reloading.
INFO 2024-04-15 19:02:04,676 autoreload 2288 13852 Watching for file changes with StatReloader
INFO 2024-04-15 19:04:09,930 autoreload 2288 13852 C:\Users\JaneM\PycharmProjects\Django\homework_1\homework_1\settings.py changed, reloading.
INFO 2024-04-15 19:04:10,541 autoreload 7708 13668 Watching for file changes with StatReloader
INFO 2024-04-15 19:06:39,301 autoreload 7708 13668 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\apps.py changed, reloading.
INFO 2024-04-15 19:06:40,246 autoreload 9796 3016 Watching for file changes with StatReloader
INFO 2024-04-15 19:08:42,169 autoreload 9796 3016 C:\Users\JaneM\PycharmProjects\Django\homework_1\homework_1\urls.py changed, reloading.
INFO 2024-04-15 19:08:42,951 autoreload 4628 14228 Watching for file changes with StatReloader
INFO 2024-04-15 19:21:21,574 autoreload 4628 14228 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\views.py changed, reloading.
INFO 2024-04-15 19:21:22,352 autoreload 13532 11840 Watching for file changes with StatReloader
INFO 2024-04-15 19:22:11,249 autoreload 13532 11840 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\views.py changed, reloading.
INFO 2024-04-15 19:22:12,063 autoreload 10600 2920 Watching for file changes with StatReloader
INFO 2024-04-15 19:24:47,218 autoreload 10600 2920 C:\Users\JaneM\PycharmProjects\Django\homework_1\homework_1\settings.py changed, reloading.
INFO 2024-04-15 19:24:54,729 autoreload 13896 7528 Watching for file changes with StatReloader
INFO 2024-04-15 19:25:37,269 autoreload 13896 7528 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\migrations\0001_initial.py changed, reloading.
INFO 2024-04-15 19:25:38,379 autoreload 8044 9976 Watching for file changes with StatReloader
INFO 2024-04-15 19:26:14,057 autoreload 8044 9976 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\migrations\0003_alter_product_image.py changed, reloading.
INFO 2024-04-15 19:26:14,864 autoreload 11328 1720 Watching for file changes with StatReloader
INFO 2024-04-15 19:26:16,537 views 11328 11576 Посещение страницы hw_app3.views: index
INFO 2024-04-15 19:26:16,629 basehttp 11328 11576 "GET / HTTP/1.1" 200 326
INFO 2024-04-15 19:29:03,806 autoreload 13440 13032 Watching for file changes with StatReloader
INFO 2024-04-15 19:29:05,377 views 13440 12564 Посещение страницы hw_app3.views: index
INFO 2024-04-15 19:29:05,392 basehttp 13440 12564 "GET / HTTP/1.1" 200 326
INFO 2024-04-15 19:30:51,206 basehttp 13440 12564 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-04-15 19:30:51,479 basehttp 13440 12564 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
INFO 2024-04-15 19:30:51,861 basehttp 13440 12564 "GET /static/admin/css/base.css HTTP/1.1" 200 21544
INFO 2024-04-15 19:30:51,890 basehttp 13440 10228 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
INFO 2024-04-15 19:30:51,900 basehttp 13440 12564 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2024-04-15 19:30:51,903 basehttp 13440 5456 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2024-04-15 19:30:51,909 basehttp 13440 10504 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2024-04-15 19:30:51,922 basehttp 13440 9648 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2024-04-15 19:30:51,922 basehttp 13440 13560 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
INFO 2024-04-15 19:31:32,148 autoreload 13440 13032 C:\Users\JaneM\PycharmProjects\Django\homework_1\homework_1\settings.py changed, reloading.
INFO 2024-04-15 19:31:33,160 autoreload 13484 6476 Watching for file changes with StatReloader
INFO 2024-04-15 19:31:39,193 basehttp 13484 9976 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-04-15 19:56:11,363 autoreload 14284 13728 Watching for file changes with StatReloader
INFO 2024-04-15 19:56:18,363 basehttp 14284 5836 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-04-15 19:56:18,439 basehttp 14284 5836 "GET /admin/ HTTP/1.1" 200 5944
INFO 2024-04-15 19:56:18,531 basehttp 14284 5836 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2024-04-15 19:56:18,591 basehttp 14284 5568 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2024-04-15 19:56:18,591 basehttp 14284 5836 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2024-04-15 19:57:12,925 basehttp 14284 5836 "GET /admin/auth/user/add/ HTTP/1.1" 200 11238
INFO 2024-04-15 19:57:12,969 basehttp 14284 1240 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2024-04-15 19:57:13,052 basehttp 14284 1240 "GET /static/admin/js/actions.js HTTP/1.1" 200 8067
INFO 2024-04-15 19:57:13,052 basehttp 14284 7364 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2024-04-15 19:57:13,135 basehttp 14284 5836 "GET /static/admin/css/forms.css HTTP/1.1" 200 9090
INFO 2024-04-15 19:57:13,135 basehttp 14284 1496 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
INFO 2024-04-15 19:57:13,166 basehttp 14284 5568 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 19:57:13,203 basehttp 14284 5568 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2024-04-15 19:57:13,229 basehttp 14284 5836 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2024-04-15 19:57:13,242 basehttp 14284 1240 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2024-04-15 19:57:13,248 basehttp 14284 2920 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2024-04-15 19:57:13,324 basehttp 14284 7364 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2024-04-15 19:57:13,427 basehttp 14284 1496 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
INFO 2024-04-15 19:57:13,547 basehttp 14284 1496 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2024-04-15 19:57:29,670 basehttp 14284 1496 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2024-04-15 19:57:29,753 basehttp 14284 1496 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 25349
INFO 2024-04-15 19:57:29,788 basehttp 14284 1496 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 19:57:29,814 basehttp 14284 5836 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
INFO 2024-04-15 19:57:29,824 basehttp 14284 1240 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2024-04-15 19:57:29,825 basehttp 14284 2920 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2024-04-15 19:57:29,833 basehttp 14284 7364 "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2024-04-15 19:57:29,907 basehttp 14284 7364 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2024-04-15 19:57:30,027 basehttp 14284 1240 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2024-04-15 19:57:30,048 basehttp 14284 5568 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2024-04-15 19:57:30,054 basehttp 14284 5836 "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2024-04-15 19:57:30,057 basehttp 14284 1496 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2024-04-15 19:57:30,062 basehttp 14284 7364 "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2024-04-15 19:57:30,070 basehttp 14284 2920 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2024-04-15 19:58:55,885 basehttp 14284 2920 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2024-04-15 19:58:55,971 basehttp 14284 2920 "GET /admin/auth/user/ HTTP/1.1" 200 12633
INFO 2024-04-15 19:58:56,012 basehttp 14284 7364 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 19:58:56,012 basehttp 14284 2920 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
INFO 2024-04-15 19:58:56,041 basehttp 14284 7364 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2024-04-15 19:58:56,045 basehttp 14284 5836 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2024-04-15 19:58:56,050 basehttp 14284 1496 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2024-04-15 19:58:56,057 basehttp 14284 2920 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2024-04-15 19:59:02,253 basehttp 14284 2920 "GET /admin/auth/group/ HTTP/1.1" 200 7783
INFO 2024-04-15 19:59:02,285 basehttp 14284 2920 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 19:59:03,503 basehttp 14284 2920 "GET /admin/auth/user/ HTTP/1.1" 200 12413
INFO 2024-04-15 19:59:03,531 basehttp 14284 2920 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 19:59:05,945 basehttp 14284 2920 "POST /admin/logout/ HTTP/1.1" 200 3817
INFO 2024-04-15 19:59:07,569 basehttp 14284 2920 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-04-15 19:59:07,583 basehttp 14284 2920 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-04-15 19:59:14,712 basehttp 14284 2920 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-04-15 19:59:14,757 basehttp 14284 2920 "GET /admin/ HTTP/1.1" 200 6706
INFO 2024-04-15 19:59:20,406 basehttp 14284 2920 "POST /admin/logout/ HTTP/1.1" 200 3817
INFO 2024-04-15 19:59:21,706 basehttp 14284 2920 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-04-15 19:59:21,719 basehttp 14284 2920 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-04-15 19:59:31,963 basehttp 14284 2920 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-04-15 19:59:31,990 basehttp 14284 2920 "GET /admin/ HTTP/1.1" 200 4889
INFO 2024-04-15 20:01:15,168 autoreload 14284 13728 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 20:01:16,109 autoreload 1828 12172 Watching for file changes with StatReloader
INFO 2024-04-15 20:08:17,088 autoreload 14004 9092 Watching for file changes with StatReloader
INFO 2024-04-15 20:08:21,515 basehttp 14004 14120 "GET /admin/ HTTP/1.1" 200 4889
INFO 2024-04-15 20:08:24,174 basehttp 14004 14120 "GET /admin/ HTTP/1.1" 200 4889
INFO 2024-04-15 20:08:25,668 basehttp 14004 14120 "POST /admin/logout/ HTTP/1.1" 200 3817
INFO 2024-04-15 20:08:27,243 basehttp 14004 14120 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-04-15 20:08:27,268 basehttp 14004 14120 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-04-15 20:08:34,728 basehttp 14004 14120 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-04-15 20:08:34,752 basehttp 14004 14120 "GET /admin/ HTTP/1.1" 200 7856
INFO 2024-04-15 20:09:39,230 basehttp 14004 14120 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 10914
INFO 2024-04-15 20:09:39,267 basehttp 14004 14120 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:10:24,055 basehttp 14004 14120 "GET /admin/hw_app5/category/add/?_to_field=id&_popup=1 HTTP/1.1" 200 4445
INFO 2024-04-15 20:10:24,087 basehttp 14004 14120 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:10:33,870 basehttp 14004 14120 "GET /admin/hw_app5/category/add/?_to_field=id&_popup=1 HTTP/1.1" 200 4445
INFO 2024-04-15 20:10:33,904 basehttp 14004 14120 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:10:47,896 basehttp 14004 14120 "POST /admin/hw_app5/category/add/?_to_field=id&_popup=1 HTTP/1.1" 200 374
INFO 2024-04-15 20:10:47,982 basehttp 14004 14120 "GET /static/admin/js/popup_response.js HTTP/1.1" 200 551
INFO 2024-04-15 20:10:51,528 basehttp 14004 14120 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 20:10:51,550 basehttp 14004 14120 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 11258
INFO 2024-04-15 20:10:51,586 basehttp 14004 14120 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:11:08,511 basehttp 14004 14120 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 20:11:08,587 basehttp 14004 14120 "GET /admin/hw_app5/product/ HTTP/1.1" 200 10409
INFO 2024-04-15 20:11:08,626 basehttp 14004 14120 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:11:11,804 basehttp 14004 14120 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 10958
INFO 2024-04-15 20:11:11,835 basehttp 14004 14120 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:11:24,338 basehttp 14004 14120 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 20:11:24,360 basehttp 14004 14120 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 11252
INFO 2024-04-15 20:11:24,400 basehttp 14004 14120 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:11:38,593 basehttp 14004 14120 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 20:11:38,627 basehttp 14004 14120 "GET /admin/hw_app5/product/ HTTP/1.1" 200 11112
INFO 2024-04-15 20:11:38,662 basehttp 14004 14120 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:59:16,657 basehttp 14004 14948 "GET /admin/hw_app5/category/add/ HTTP/1.1" 200 9124
INFO 2024-04-15 20:59:16,725 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:59:26,609 basehttp 14004 14948 "POST /admin/hw_app5/category/add/ HTTP/1.1" 302 0
INFO 2024-04-15 20:59:26,629 basehttp 14004 14948 "GET /admin/hw_app5/category/ HTTP/1.1" 200 10355
INFO 2024-04-15 20:59:26,658 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:59:31,239 basehttp 14004 14948 "GET /admin/hw_app5/product/ HTTP/1.1" 200 10889
INFO 2024-04-15 20:59:31,269 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 20:59:34,542 basehttp 14004 14948 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 10997
INFO 2024-04-15 20:59:34,569 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:00:10,783 basehttp 14004 14948 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 21:00:10,827 basehttp 14004 14948 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 11313
INFO 2024-04-15 21:00:10,859 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:00:27,323 basehttp 14004 14948 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 21:00:27,359 basehttp 14004 14948 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 11314
INFO 2024-04-15 21:00:27,396 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:00:48,878 basehttp 14004 14948 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 21:00:48,893 basehttp 14004 14948 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 11309
INFO 2024-04-15 21:00:48,929 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:01:10,678 basehttp 14004 14948 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 21:01:10,698 basehttp 14004 14948 "GET /admin/hw_app5/product/ HTTP/1.1" 200 12724
INFO 2024-04-15 21:01:10,733 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:01:24,338 basehttp 14004 14948 "GET /admin/hw_app5/category/ HTTP/1.1" 200 10142
INFO 2024-04-15 21:01:24,368 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:01:26,000 basehttp 14004 14948 "GET /admin/hw_app5/category/2/change/ HTTP/1.1" 200 9350
INFO 2024-04-15 21:01:26,033 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:01:30,088 basehttp 14004 14948 "POST /admin/hw_app5/category/2/change/ HTTP/1.1" 302 0
INFO 2024-04-15 21:01:30,111 basehttp 14004 14948 "GET /admin/hw_app5/category/ HTTP/1.1" 200 10357
INFO 2024-04-15 21:01:30,148 basehttp 14004 14948 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:02:46,557 autoreload 14004 9092 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 21:02:49,178 autoreload 13684 10728 Watching for file changes with StatReloader
INFO 2024-04-15 21:05:32,174 autoreload 13684 10728 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\admin.py changed, reloading.
INFO 2024-04-15 21:05:32,991 autoreload 10580 14156 Watching for file changes with StatReloader
INFO 2024-04-15 21:05:56,027 basehttp 10580 7512 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11300
INFO 2024-04-15 21:05:56,053 basehttp 10580 7512 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
WARNING 2024-04-15 21:06:26,479 log 10580 7512 Not Found: /admin/myapp3/author/
WARNING 2024-04-15 21:06:26,481 basehttp 10580 7512 "GET /admin/myapp3/author/ HTTP/1.1" 404 5200
INFO 2024-04-15 21:06:49,102 basehttp 10580 7512 "GET /admin/hw_app3/product/ HTTP/1.1" 200 18351
INFO 2024-04-15 21:06:49,142 basehttp 10580 7512 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:07:09,395 basehttp 10580 7512 "GET /admin/hw_app5/category/2/change/ HTTP/1.1" 200 10508
INFO 2024-04-15 21:07:09,428 basehttp 10580 7512 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:07:18,626 basehttp 10580 7512 "POST /admin/hw_app5/category/2/change/ HTTP/1.1" 302 0
INFO 2024-04-15 21:07:18,676 basehttp 10580 7512 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11512
INFO 2024-04-15 21:07:18,713 basehttp 10580 7512 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:07:20,743 basehttp 10580 7512 "GET /admin/hw_app3/product/ HTTP/1.1" 200 18351
INFO 2024-04-15 21:07:20,769 basehttp 10580 7512 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:07:23,455 basehttp 10580 7512 "GET /admin/hw_app5/product/ HTTP/1.1" 200 13633
INFO 2024-04-15 21:07:23,482 basehttp 10580 7512 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:07:24,957 basehttp 10580 7512 "GET /admin/hw_app5/product/8/change/ HTTP/1.1" 200 12532
INFO 2024-04-15 21:07:24,991 basehttp 10580 7512 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:07:27,199 basehttp 10580 7512 "GET /admin/hw_app5/product/ HTTP/1.1" 200 13633
INFO 2024-04-15 21:12:57,153 autoreload 10580 14156 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 21:12:58,043 autoreload 13100 10380 Watching for file changes with StatReloader
INFO 2024-04-15 21:13:32,903 autoreload 13100 10380 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 21:13:33,838 autoreload 13540 10584 Watching for file changes with StatReloader
INFO 2024-04-15 21:18:48,685 autoreload 13344 12980 Watching for file changes with StatReloader
INFO 2024-04-15 21:18:50,658 views 13344 5504 Посещение страницы hw_app3.views: index
INFO 2024-04-15 21:18:50,675 basehttp 13344 5504 "GET / HTTP/1.1" 200 326
INFO 2024-04-15 21:19:08,209 basehttp 13344 5504 "GET /admin HTTP/1.1" 301 0
INFO 2024-04-15 21:19:08,295 basehttp 13344 13628 "GET /admin/ HTTP/1.1" 200 12465
INFO 2024-04-15 21:19:30,879 basehttp 13344 13628 "GET /admin/ HTTP/1.1" 200 12465
INFO 2024-04-15 21:20:15,615 basehttp 13344 13628 "GET /admin/hw_app3/product/ HTTP/1.1" 200 18351
INFO 2024-04-15 21:20:15,657 basehttp 13344 13628 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:20:17,924 basehttp 13344 13628 "GET /admin/hw_app5/product/ HTTP/1.1" 200 13633
INFO 2024-04-15 21:20:17,955 basehttp 13344 13628 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:29:50,760 autoreload 13344 12980 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 21:29:51,600 autoreload 13744 12584 Watching for file changes with StatReloader
INFO 2024-04-15 21:36:27,838 autoreload 13744 12584 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 21:36:28,552 autoreload 9532 11880 Watching for file changes with StatReloader
INFO 2024-04-15 21:36:34,201 basehttp 9532 6436 "GET /admin/hw_app5/product/ HTTP/1.1" 200 17353
INFO 2024-04-15 21:36:34,251 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:39:25,340 basehttp 9532 6436 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11298
INFO 2024-04-15 21:39:25,372 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:39:27,496 basehttp 9532 6436 "GET /admin/hw_app5/product/ HTTP/1.1" 200 17353
INFO 2024-04-15 21:39:27,525 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:39:28,761 basehttp 9532 6436 "GET /admin/hw_app5/product/4/change/ HTTP/1.1" 200 16085
INFO 2024-04-15 21:39:28,793 basehttp 9532 9296 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:39:28,857 basehttp 9532 6436 "GET /static/admin/js/collapse.js HTTP/1.1" 200 1803
INFO 2024-04-15 21:40:24,200 basehttp 9532 6436 "POST /admin/hw_app5/product/4/change/ HTTP/1.1" 302 0
INFO 2024-04-15 21:40:24,242 basehttp 9532 6436 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 16061
INFO 2024-04-15 21:40:24,279 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:40:26,006 basehttp 9532 6436 "POST /admin/hw_app5/product/add/ HTTP/1.1" 200 16085
INFO 2024-04-15 21:40:26,033 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:40:39,154 basehttp 9532 6436 "GET /admin/hw_app5/product/ HTTP/1.1" 200 17410
INFO 2024-04-15 21:40:39,190 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:40:42,388 basehttp 9532 6436 "GET /admin/hw_app5/product/3/change/ HTTP/1.1" 200 16077
INFO 2024-04-15 21:40:42,426 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:42:09,635 basehttp 9532 6436 "POST /admin/hw_app5/product/3/change/ HTTP/1.1" 302 0
INFO 2024-04-15 21:42:09,658 basehttp 9532 6436 "GET /admin/hw_app5/product/ HTTP/1.1" 200 17690
INFO 2024-04-15 21:42:09,693 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:42:12,007 basehttp 9532 6436 "GET /admin/hw_app5/product/8/change/ HTTP/1.1" 200 16189
INFO 2024-04-15 21:42:12,037 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:43:02,454 basehttp 9532 6436 "POST /admin/hw_app5/product/8/change/ HTTP/1.1" 302 0
INFO 2024-04-15 21:43:02,484 basehttp 9532 6436 "GET /admin/hw_app5/product/ HTTP/1.1" 200 17775
INFO 2024-04-15 21:43:02,519 basehttp 9532 6436 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 21:44:27,471 autoreload 9532 11880 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 21:44:28,556 autoreload 5528 14796 Watching for file changes with StatReloader
INFO 2024-04-15 21:55:35,623 autoreload 5528 14796 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 21:55:36,683 autoreload 13704 8408 Watching for file changes with StatReloader
INFO 2024-04-15 21:57:44,736 autoreload 13704 8408 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 21:57:45,789 autoreload 7872 3008 Watching for file changes with StatReloader
INFO 2024-04-15 22:02:21,368 autoreload 7872 3008 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 22:02:22,527 autoreload 636 14156 Watching for file changes with StatReloader
INFO 2024-04-15 22:03:44,908 autoreload 636 14156 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:03:45,768 autoreload 6124 8316 Watching for file changes with StatReloader
INFO 2024-04-15 22:03:58,187 autoreload 6124 8316 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:03:59,126 autoreload 6960 14592 Watching for file changes with StatReloader
INFO 2024-04-15 22:04:51,592 autoreload 6960 14592 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:04:52,440 autoreload 9308 15252 Watching for file changes with StatReloader
INFO 2024-04-15 22:05:04,450 autoreload 9308 15252 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:05:05,135 autoreload 7896 11736 Watching for file changes with StatReloader
INFO 2024-04-15 22:09:14,406 autoreload 7896 11736 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:09:15,201 autoreload 8196 2236 Watching for file changes with StatReloader
INFO 2024-04-15 22:10:32,441 autoreload 8196 2236 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 22:10:33,257 autoreload 13100 13496 Watching for file changes with StatReloader
INFO 2024-04-15 22:10:47,272 autoreload 13100 13496 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 22:10:48,015 autoreload 12860 13868 Watching for file changes with StatReloader
INFO 2024-04-15 22:14:35,637 autoreload 12860 13868 C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\related.py changed, reloading.
INFO 2024-04-15 22:14:36,368 autoreload 1824 1032 Watching for file changes with StatReloader
INFO 2024-04-15 22:16:30,938 autoreload 1824 1032 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:16:31,742 autoreload 9444 7244 Watching for file changes with StatReloader
INFO 2024-04-15 22:16:39,003 basehttp 9444 3864 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18130
INFO 2024-04-15 22:16:39,045 basehttp 9444 3864 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
ERROR 2024-04-15 22:16:44,501 log 9444 3864 Internal Server Error: /admin/hw_app5/order/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: hw_app5_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 144, in __init__
    self.queryset = self.get_queryset(request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 539, in get_queryset
    ) = self.get_filters(request)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 215, in get_filters
    spec = field_list_filter_class(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 217, in create
    return list_filter_class(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1079, in get_choices
    return (blank_choice if include_blank else []) + [
                                                     ^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: hw_app5_client
ERROR 2024-04-15 22:16:44,520 basehttp 9444 3864 "GET /admin/hw_app5/order/ HTTP/1.1" 500 214150
INFO 2024-04-15 22:16:52,936 basehttp 9444 3864 "GET /admin/hw_app5/ HTTP/1.1" 200 6764
INFO 2024-04-15 22:16:58,705 basehttp 9444 3864 "GET /admin/ HTTP/1.1" 200 13390
INFO 2024-04-15 22:17:08,781 basehttp 9444 3864 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11904
INFO 2024-04-15 22:17:08,819 basehttp 9444 3864 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
ERROR 2024-04-15 22:17:12,122 log 9444 3864 Internal Server Error: /admin/hw_app5/client/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: hw_app5_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.get_results(request)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 312, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
           ^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 629, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 615, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: hw_app5_client
ERROR 2024-04-15 22:17:12,141 basehttp 9444 3864 "GET /admin/hw_app5/client/ HTTP/1.1" 500 195767
INFO 2024-04-15 22:17:14,700 basehttp 9444 3864 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11904
INFO 2024-04-15 22:17:16,839 basehttp 9444 3864 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18130
INFO 2024-04-15 22:17:16,874 basehttp 9444 3864 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:17:20,831 basehttp 9444 3864 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11904
ERROR 2024-04-15 22:17:22,225 log 9444 3864 Internal Server Error: /admin/hw_app5/order/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: hw_app5_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 144, in __init__
    self.queryset = self.get_queryset(request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 539, in get_queryset
    ) = self.get_filters(request)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 215, in get_filters
    spec = field_list_filter_class(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 217, in create
    return list_filter_class(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1079, in get_choices
    return (blank_choice if include_blank else []) + [
                                                     ^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: hw_app5_client
ERROR 2024-04-15 22:17:22,236 basehttp 9444 3864 "GET /admin/hw_app5/order/ HTTP/1.1" 500 214151
INFO 2024-04-15 22:26:17,380 autoreload 9444 7244 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:26:18,159 autoreload 3264 14840 Watching for file changes with StatReloader
INFO 2024-04-15 22:29:31,075 autoreload 1376 4788 Watching for file changes with StatReloader
INFO 2024-04-15 22:30:59,555 autoreload 1376 4788 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:31:00,387 autoreload 14656 6792 Watching for file changes with StatReloader
INFO 2024-04-15 22:31:24,226 autoreload 14656 6792 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:31:25,017 autoreload 11156 11516 Watching for file changes with StatReloader
ERROR 2024-04-15 22:31:31,123 log 11156 14320 Internal Server Error: /admin/hw_app5/order/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: hw_app5_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 144, in __init__
    self.queryset = self.get_queryset(request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 539, in get_queryset
    ) = self.get_filters(request)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 215, in get_filters
    spec = field_list_filter_class(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 217, in create
    return list_filter_class(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1079, in get_choices
    return (blank_choice if include_blank else []) + [
                                                     ^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: hw_app5_client
ERROR 2024-04-15 22:31:31,136 basehttp 11156 14320 "GET /admin/hw_app5/order/ HTTP/1.1" 500 214158
ERROR 2024-04-15 22:31:34,046 log 11156 14320 Internal Server Error: /admin/hw_app5/order/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: hw_app5_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 144, in __init__
    self.queryset = self.get_queryset(request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 539, in get_queryset
    ) = self.get_filters(request)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 215, in get_filters
    spec = field_list_filter_class(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 217, in create
    return list_filter_class(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1079, in get_choices
    return (blank_choice if include_blank else []) + [
                                                     ^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: hw_app5_client
ERROR 2024-04-15 22:31:34,059 basehttp 11156 14320 "GET /admin/hw_app5/order/ HTTP/1.1" 500 214158
INFO 2024-04-15 22:33:46,816 autoreload 10144 13244 Watching for file changes with StatReloader
INFO 2024-04-15 22:33:50,997 basehttp 10144 7692 "GET /admin/hw_app5/order/ HTTP/1.1" 200 11652
INFO 2024-04-15 22:33:51,043 basehttp 10144 7692 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:33:54,639 basehttp 10144 7692 "GET /admin/hw_app5/client/ HTTP/1.1" 200 10362
INFO 2024-04-15 22:33:54,671 basehttp 10144 7692 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:33:56,623 basehttp 10144 7692 "GET /admin/hw_app5/order/ HTTP/1.1" 200 11652
INFO 2024-04-15 22:33:56,653 basehttp 10144 7692 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:33:58,639 basehttp 10144 7692 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18130
INFO 2024-04-15 22:33:58,670 basehttp 10144 7692 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:34:01,357 basehttp 10144 7692 "GET /admin/hw_app5/order/ HTTP/1.1" 200 11652
INFO 2024-04-15 22:34:01,388 basehttp 10144 7692 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:34:02,135 basehttp 10144 7692 "GET /admin/hw_app5/client/ HTTP/1.1" 200 10362
INFO 2024-04-15 22:34:02,165 basehttp 10144 7692 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:34:33,825 autoreload 11524 13804 Watching for file changes with StatReloader
INFO 2024-04-15 22:34:46,686 views 11524 10852 Посещение страницы hw_app3.views: index
INFO 2024-04-15 22:34:46,696 basehttp 11524 10852 "GET / HTTP/1.1" 200 326
INFO 2024-04-15 22:34:52,312 basehttp 11524 10852 "GET /admin/ HTTP/1.1" 200 13390
INFO 2024-04-15 22:34:57,525 basehttp 11524 10852 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18130
INFO 2024-04-15 22:34:57,562 basehttp 11524 10852 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:34:59,553 basehttp 11524 10852 "GET /admin/hw_app5/order/ HTTP/1.1" 200 11652
INFO 2024-04-15 22:34:59,582 basehttp 11524 10852 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:35:01,713 basehttp 11524 10852 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 13880
INFO 2024-04-15 22:35:01,741 basehttp 11524 10852 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:35:05,422 basehttp 11524 10852 "GET /admin/hw_app5/client/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6316
INFO 2024-04-15 22:35:05,450 basehttp 11524 10852 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:35:25,627 basehttp 11524 10852 "POST /admin/hw_app5/client/add/?_to_field=id&_popup=1 HTTP/1.1" 200 365
ERROR 2024-04-15 22:35:29,453 log 11524 10852 Internal Server Error: /admin/hw_app5/order/add/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: hw_app5_order.total

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1259, in save_model
    obj.save()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: hw_app5_order.total
ERROR 2024-04-15 22:35:29,465 basehttp 11524 10852 "POST /admin/hw_app5/order/add/ HTTP/1.1" 500 206117
INFO 2024-04-15 22:38:11,954 autoreload 11524 13804 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\apps.py changed, reloading.
INFO 2024-04-15 22:38:12,895 autoreload 7380 14516 Watching for file changes with StatReloader
INFO 2024-04-15 22:38:18,045 basehttp 7380 2060 "GET /admin/hw_app5/ HTTP/1.1" 200 6764
INFO 2024-04-15 22:38:23,062 basehttp 7380 2060 "GET /admin/ HTTP/1.1" 200 13382
INFO 2024-04-15 22:38:31,482 basehttp 7380 2060 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18130
INFO 2024-04-15 22:38:31,520 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:38:34,500 basehttp 7380 2060 "GET /admin/hw_app5/product/add/ HTTP/1.1" 200 16388
INFO 2024-04-15 22:38:34,535 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:39:24,579 basehttp 7380 2060 "POST /admin/hw_app5/product/add/ HTTP/1.1" 200 16618
INFO 2024-04-15 22:39:24,608 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:39:32,442 basehttp 7380 2060 "POST /admin/hw_app5/product/add/ HTTP/1.1" 302 0
INFO 2024-04-15 22:39:32,466 basehttp 7380 2060 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18838
INFO 2024-04-15 22:39:32,498 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:39:35,591 basehttp 7380 2060 "GET /admin/hw_app5/order/ HTTP/1.1" 200 11728
INFO 2024-04-15 22:39:35,622 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:39:39,059 basehttp 7380 2060 "GET /admin/hw_app5/client/add/ HTTP/1.1" 200 12753
INFO 2024-04-15 22:39:39,085 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:39:52,714 basehttp 7380 2060 "POST /admin/hw_app5/client/add/ HTTP/1.1" 200 13041
INFO 2024-04-15 22:39:52,743 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:40:02,180 basehttp 7380 2060 "POST /admin/hw_app5/client/add/ HTTP/1.1" 302 0
INFO 2024-04-15 22:40:02,231 basehttp 7380 2060 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13184
INFO 2024-04-15 22:40:02,268 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:40:15,281 basehttp 7380 2060 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 13951
INFO 2024-04-15 22:40:15,314 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
ERROR 2024-04-15 22:40:30,794 log 7380 2060 Internal Server Error: /admin/hw_app5/order/add/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: hw_app5_order.total

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1259, in save_model
    obj.save()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: hw_app5_order.total
ERROR 2024-04-15 22:40:30,807 basehttp 7380 2060 "POST /admin/hw_app5/order/add/ HTTP/1.1" 500 206169
INFO 2024-04-15 22:40:37,436 basehttp 7380 2060 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 13951
INFO 2024-04-15 22:40:42,872 basehttp 7380 2060 "GET /admin/hw_app5/order/ HTTP/1.1" 200 12028
INFO 2024-04-15 22:40:42,902 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:40:44,474 basehttp 7380 2060 "GET /admin/hw_app5/client/ HTTP/1.1" 200 12978
INFO 2024-04-15 22:40:44,500 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:40:48,610 basehttp 7380 2060 "GET /admin/hw_app5/client/add/ HTTP/1.1" 200 12753
INFO 2024-04-15 22:40:48,640 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:40:58,227 basehttp 7380 2060 "POST /admin/hw_app5/client/add/ HTTP/1.1" 200 13129
INFO 2024-04-15 22:40:58,255 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:11,304 basehttp 7380 2060 "POST /admin/hw_app5/client/add/ HTTP/1.1" 302 0
INFO 2024-04-15 22:41:11,324 basehttp 7380 2060 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13596
INFO 2024-04-15 22:41:11,358 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:16,827 basehttp 7380 2060 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11904
INFO 2024-04-15 22:41:16,853 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:18,468 basehttp 7380 2060 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13391
INFO 2024-04-15 22:41:18,501 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:21,717 basehttp 7380 2060 "GET /admin/hw_app5/order/ HTTP/1.1" 200 12091
INFO 2024-04-15 22:41:21,745 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:23,341 basehttp 7380 2060 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13391
INFO 2024-04-15 22:41:23,368 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:24,606 basehttp 7380 2060 "GET /admin/hw_app5/client/3/change/ HTTP/1.1" 200 13035
INFO 2024-04-15 22:41:24,635 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:32,137 basehttp 7380 2060 "GET /admin/hw_app5/order/ HTTP/1.1" 200 12091
INFO 2024-04-15 22:41:32,164 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:35,101 basehttp 7380 2060 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 13986
INFO 2024-04-15 22:41:35,129 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:41:59,600 basehttp 7380 2060 "GET /admin/hw_app5/client/1/change/?_to_field=id HTTP/1.1" 200 13082
INFO 2024-04-15 22:41:59,636 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:42:02,616 basehttp 7380 2060 "POST /admin/hw_app5/client/1/change/?_to_field=id HTTP/1.1" 302 0
INFO 2024-04-15 22:42:02,637 basehttp 7380 2060 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13598
INFO 2024-04-15 22:42:02,671 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:42:04,952 basehttp 7380 2060 "GET /admin/hw_app5/order/ HTTP/1.1" 200 12091
INFO 2024-04-15 22:42:04,981 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:42:10,831 basehttp 7380 2060 "GET /admin/auth/group/ HTTP/1.1" 200 10412
INFO 2024-04-15 22:42:10,856 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:42:12,254 basehttp 7380 2060 "GET /admin/auth/user/ HTTP/1.1" 200 15042
INFO 2024-04-15 22:42:12,285 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:42:16,482 basehttp 7380 2060 "GET /admin/hw_app3/product/ HTTP/1.1" 200 18957
INFO 2024-04-15 22:42:16,508 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:42:18,031 basehttp 7380 2060 "GET /admin/hw_app3/order/ HTTP/1.1" 200 22513
INFO 2024-04-15 22:42:18,060 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:42:19,185 basehttp 7380 2060 "GET /admin/hw_app3/client/ HTTP/1.1" 200 19977
INFO 2024-04-15 22:42:19,214 basehttp 7380 2060 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:46:25,987 autoreload 7380 14516 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 22:46:27,147 autoreload 14164 7568 Watching for file changes with StatReloader
INFO 2024-04-15 22:48:48,567 autoreload 14164 7568 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\models.py changed, reloading.
INFO 2024-04-15 22:48:49,573 autoreload 12964 10296 Watching for file changes with StatReloader
INFO 2024-04-15 22:48:53,087 basehttp 12964 13524 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 22:48:53,117 basehttp 12964 13524 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
ERROR 2024-04-15 22:48:55,247 log 12964 13524 Internal Server Error: /admin/hw_app5/order/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: hw_app5_order.client_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: hw_app5_order.client_id
ERROR 2024-04-15 22:48:55,258 basehttp 12964 13524 "GET /admin/hw_app5/order/ HTTP/1.1" 500 177101
INFO 2024-04-15 22:48:57,876 basehttp 12964 13524 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 22:48:59,302 basehttp 12964 13524 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13391
INFO 2024-04-15 22:48:59,330 basehttp 12964 13524 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:49:01,432 basehttp 12964 13524 "GET /admin/hw_app5/client/3/change/ HTTP/1.1" 200 13035
INFO 2024-04-15 22:49:01,465 basehttp 12964 13524 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:07,052 autoreload 9684 7624 Watching for file changes with StatReloader
INFO 2024-04-15 22:51:08,767 views 9684 11804 Посещение страницы hw_app3.views: index
INFO 2024-04-15 22:51:08,798 basehttp 9684 11804 "GET / HTTP/1.1" 200 326
INFO 2024-04-15 22:51:15,938 basehttp 9684 11804 "GET /admin/ HTTP/1.1" 200 13248
INFO 2024-04-15 22:51:19,239 basehttp 9684 11804 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13391
INFO 2024-04-15 22:51:19,272 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:21,159 basehttp 9684 11804 "GET /admin/hw_app5/client/3/change/ HTTP/1.1" 200 13035
INFO 2024-04-15 22:51:21,187 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:27,701 basehttp 9684 11804 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11904
INFO 2024-04-15 22:51:27,728 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:29,467 basehttp 9684 11804 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13391
INFO 2024-04-15 22:51:29,494 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:30,868 basehttp 9684 11804 "GET /admin/hw_app5/order/ HTTP/1.1" 200 12081
INFO 2024-04-15 22:51:30,894 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:32,761 basehttp 9684 11804 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 22:51:32,788 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:34,569 basehttp 9684 11804 "GET /admin/hw_app5/product/4/change/ HTTP/1.1" 200 17216
INFO 2024-04-15 22:51:34,596 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:43,266 basehttp 9684 11804 "POST /admin/hw_app5/product/4/change/ HTTP/1.1" 302 0
INFO 2024-04-15 22:51:43,303 basehttp 9684 11804 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18843
INFO 2024-04-15 22:51:43,332 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:45,024 basehttp 9684 11804 "GET /admin/hw_app5/order/ HTTP/1.1" 200 12081
INFO 2024-04-15 22:51:45,053 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:51:46,880 basehttp 9684 11804 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 13970
INFO 2024-04-15 22:51:46,909 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
ERROR 2024-04-15 22:51:56,558 log 9684 11804 Internal Server Error: /admin/hw_app5/order/add/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: hw_app5_order.total

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1259, in save_model
    obj.save()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: hw_app5_order.total
ERROR 2024-04-15 22:51:56,576 basehttp 9684 11804 "POST /admin/hw_app5/order/add/ HTTP/1.1" 500 206081
INFO 2024-04-15 22:52:07,923 basehttp 9684 11804 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 13970
INFO 2024-04-15 22:52:08,907 basehttp 9684 11804 "GET /admin/hw_app5/order/ HTTP/1.1" 200 12081
INFO 2024-04-15 22:52:14,123 basehttp 9684 11804 "GET /admin/hw_app5/order/?_facets=True HTTP/1.1" 200 12469
INFO 2024-04-15 22:52:14,151 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:52:14,254 basehttp 9684 11804 "GET /static/admin/img/icon-hidelink.svg HTTP/1.1" 200 784
INFO 2024-04-15 22:52:15,475 basehttp 9684 11804 "GET /admin/hw_app5/order/? HTTP/1.1" 200 12081
INFO 2024-04-15 22:52:15,501 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:52:28,673 basehttp 9684 11804 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 13970
INFO 2024-04-15 22:52:28,706 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:52:45,899 basehttp 9684 11804 "GET /admin/hw_app5/client/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6316
INFO 2024-04-15 22:52:45,924 basehttp 9684 11804 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:52:49,731 basehttp 9684 11804 "GET /admin/hw_app5/order/? HTTP/1.1" 200 12081
INFO 2024-04-15 22:55:10,826 autoreload 9684 7624 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:55:11,840 autoreload 9880 13576 Watching for file changes with StatReloader
INFO 2024-04-15 22:59:11,722 autoreload 9880 13576 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 22:59:12,503 autoreload 8264 14460 Watching for file changes with StatReloader
INFO 2024-04-15 22:59:20,193 basehttp 8264 13520 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13391
INFO 2024-04-15 22:59:20,228 basehttp 8264 13520 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:59:23,057 basehttp 8264 13520 "GET /admin/hw_app5/category/ HTTP/1.1" 200 11904
INFO 2024-04-15 22:59:23,089 basehttp 8264 13520 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:59:24,044 basehttp 8264 13520 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 22:59:24,071 basehttp 8264 13520 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:59:25,221 basehttp 8264 13520 "GET /admin/hw_app5/order/ HTTP/1.1" 200 12081
INFO 2024-04-15 22:59:25,247 basehttp 8264 13520 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 22:59:26,800 basehttp 8264 13520 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 15353
INFO 2024-04-15 22:59:26,829 basehttp 8264 13520 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
ERROR 2024-04-15 22:59:43,795 log 8264 13520 Internal Server Error: /admin/hw_app5/order/add/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: hw_app5_order.total

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1259, in save_model
    obj.save()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: hw_app5_order.total
ERROR 2024-04-15 22:59:43,813 basehttp 8264 13520 "POST /admin/hw_app5/order/add/ HTTP/1.1" 500 206228
INFO 2024-04-15 22:59:55,264 basehttp 8264 13520 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 15353
ERROR 2024-04-15 23:00:06,229 log 8264 13520 Internal Server Error: /admin/hw_app5/order/add/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: hw_app5_order.total

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1259, in save_model
    obj.save()
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: hw_app5_order.total
ERROR 2024-04-15 23:00:06,238 basehttp 8264 13520 "POST /admin/hw_app5/order/add/ HTTP/1.1" 500 206280
INFO 2024-04-15 23:04:10,372 autoreload 8264 14460 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 23:04:11,190 autoreload 13724 5744 Watching for file changes with StatReloader
INFO 2024-04-15 23:04:43,356 autoreload 13724 5744 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 23:04:44,116 autoreload 10220 976 Watching for file changes with StatReloader
INFO 2024-04-15 23:04:54,277 basehttp 10220 14432 "GET /admin/ HTTP/1.1" 200 13258
INFO 2024-04-15 23:04:57,703 basehttp 10220 14432 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13391
INFO 2024-04-15 23:04:57,739 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:04:59,612 basehttp 10220 14432 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 23:04:59,640 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:05:00,903 basehttp 10220 14432 "GET /admin/hw_app5/order/ HTTP/1.1" 200 11526
INFO 2024-04-15 23:05:00,931 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:05:02,968 basehttp 10220 14432 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 14822
INFO 2024-04-15 23:05:03,005 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:05:28,890 basehttp 10220 14432 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 23:05:28,921 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:05:33,746 basehttp 10220 14432 "GET /admin/hw_app5/order/ HTTP/1.1" 200 11526
INFO 2024-04-15 23:05:33,776 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:05:37,294 basehttp 10220 14432 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 14822
INFO 2024-04-15 23:05:37,323 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:05:48,470 basehttp 10220 14432 "POST /admin/hw_app5/order/add/ HTTP/1.1" 302 0
INFO 2024-04-15 23:05:48,492 basehttp 10220 14432 "GET /admin/hw_app5/order/ HTTP/1.1" 200 13662
INFO 2024-04-15 23:05:48,529 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:05:57,000 basehttp 10220 14432 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 23:05:57,030 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:06:00,732 basehttp 10220 14432 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 23:06:00,756 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:06:05,273 basehttp 10220 14432 "GET /admin/hw_app5/order/ HTTP/1.1" 200 13449
INFO 2024-04-15 23:06:05,305 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:06:07,783 basehttp 10220 14432 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 23:06:07,813 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:06:14,330 basehttp 10220 14432 "GET /admin/hw_app5/order/ HTTP/1.1" 200 13449
INFO 2024-04-15 23:06:14,358 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:06:19,013 basehttp 10220 14432 "GET /admin/hw_app5/order/add/ HTTP/1.1" 200 14822
INFO 2024-04-15 23:06:19,047 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:06:30,757 basehttp 10220 14432 "POST /admin/hw_app5/order/add/ HTTP/1.1" 302 0
INFO 2024-04-15 23:06:30,793 basehttp 10220 14432 "GET /admin/hw_app5/order/ HTTP/1.1" 200 14107
INFO 2024-04-15 23:06:30,834 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:06:35,977 basehttp 10220 14432 "GET /admin/hw_app5/product/ HTTP/1.1" 200 18618
INFO 2024-04-15 23:06:36,004 basehttp 10220 14432 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:07:16,493 autoreload 10220 976 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app5\admin.py changed, reloading.
INFO 2024-04-15 23:07:17,355 autoreload 11104 7988 Watching for file changes with StatReloader
INFO 2024-04-15 23:07:22,072 basehttp 11104 13560 "GET /admin/hw_app5/client/ HTTP/1.1" 200 13391
INFO 2024-04-15 23:07:22,103 basehttp 11104 13560 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-15 23:07:23,179 basehttp 11104 13560 "GET /admin/hw_app5/order/ HTTP/1.1" 200 13894
INFO 2024-04-15 23:07:23,208 basehttp 11104 13560 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
